<a href="https://colab.research.google.com/github/MackenzieRip/DataSci/blob/main/Mackenzie_Ripley_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [1]:
for i in range(100):    #showing the first 100 numbers
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [2]:
for i in range(5,8):   #showing numbers from 5 to 8
    print(i)

5
6
7


In [3]:
for i in range(3):    #showing numbers from 0 to 3
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [4]:
def square(x):         #defining square
    return x**2

In [5]:
square(5)    #squaring 5

25

In [6]:
square(square(2))   #squaring 2 squared

16

In [7]:
square(square(square(2)))   #squaring 2 squared squared


256

In [8]:
square(123456)   #squaring 123456

15241383936

In [9]:
square(square(5))  #squaring 5 squared

625

In [10]:
def add_two(x):      #defining add_two
    return x+2

In [11]:
add_two(5)   #adding 2 to 5

7

In [12]:
square(add_two(5)) #adding 2 to 5 then squaring it

49

### Logical Branching

In [13]:
choice = "apple"    #defining choice as apple

In [14]:
if choice == "apple":          #telling what to say depending on the choice

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [15]:
choice = "orange"    #defining choice as orange

In [16]:
if choice == "apple":           #didn't choose apples 
 
    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [17]:
choice = "apple"   #defining choice as apple

In [18]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [19]:
choice = input("Please enter your choice (i.e. apple): ")          #choosing something to insert

Please enter your choice (i.e. apple): apple


In [20]:
choice      #the choice I made

'apple'

In [21]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

In [23]:
np.random.random()

NameError: ignored

In [ ]:
np.random.random() > 0.5  #random number is greater then 0.5

In [ ]:
def flip_coin():                             
    if np.random.random() > 0.5:   #if number is greater heads
        print("Heads")
    else:
        print("Tails")             #if not tails

In [ ]:
flip_coin()  #flips coin

### Graphics Output

In [28]:
from IPython.core.display import display, HTML

In [29]:
display(HTML('<h1>Hello, world!</h1>'))

In [30]:
def coin():
  return np.random.randint(2)

In [31]:
coin()

NameError: ignored

In [ ]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [ ]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
show_img(heads)

In [ ]:
show_img(tails)

In [ ]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [ ]:
flip_coin()

In [ ]:
for i in range(5):
    flip_coin()

In [ ]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [32]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [33]:
a = np.arange(52)

NameError: ignored

In [ ]:
shuffle(a)

In [ ]:
np.random.permutation(52)

### Speed Test

In [34]:
%%timeit
shuffle(a)

NameError: ignored

In [35]:
%%timeit
np.random.permutation(52)

NameError: ignored

In [36]:
import numpy as np

In [37]:
np.random.permutation(52)

array([28, 36, 41, 24, 26, 39, 35,  3, 32, 45, 15,  9, 40, 18, 12, 30,  0,
       50,  8, 42,  1, 20, 38, 23, 51, 48, 19, 14, 22, 21, 31, 16, 47,  4,
       25, 34,  5, 37, 33, 11,  6, 43,  7, 44, 46,  2, 10, 27, 49, 13, 17,
       29])

In [38]:
cards = np.random.permutation(52)

In [39]:
cards

array([26,  9, 12, 11, 40,  8, 33, 37, 24, 25,  1, 31, 15, 46, 36,  0, 17,
       47, 14, 13, 19,  3, 32, 45,  5, 35, 48, 51, 39,  2, 22, 27, 34, 42,
       28, 10,  6, 29, 23, 38, 21, 44, 49, 30,  4,  7, 20, 50, 41, 16, 18,
       43])

In [40]:
cards[0]

26

In [41]:
cards[1]

9

In [42]:
cards[2]

12

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [43]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [44]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [45]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [46]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [47]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [48]:
card_name(0)

'Ace of Clubs'

In [49]:
card_name(51)

'King of Diamonds'

In [50]:
cards = np.random.permutation(52)

In [51]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [52]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Three of Diamonds', 'Two of Spades', 'King of Spades')

In [53]:
for i in range(5):
    print(card_name(cards[i]))

Three of Diamonds
Two of Spades
Five of Hearts
Jack of Spades
Three of Hearts


In [54]:
for i in range(15):
    print(card_name(cards[i]))

Three of Diamonds
Two of Spades
Five of Hearts
Jack of Spades
Three of Hearts
Ace of Hearts
Four of Hearts
Queen of Clubs
Ace of Diamonds
Queen of Spades
Queen of Hearts
Eight of Spades
Four of Diamonds
Nine of Spades
Ace of Clubs


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [55]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [56]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [57]:
i = np.random.randint(4)
j = np.random.randint(13)

In [58]:
i,j

(1, 10)

In [59]:
suit[i]

'p'

In [60]:
card[j]

'j'

In [61]:
from IPython.core.display import display, HTML

In [62]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [63]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [64]:
show_img(img)

In [65]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [66]:
card_image(3)

'k4'

In [67]:
img = card_url_head + card_image(3) + card_url_tail

In [68]:
show_img(img)

In [69]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)